# Generated by Django 4.1 on 2024-06-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="re_people_num",
            field=models.IntegerField(default=0),
        ),
    ]
